### ISSUE TITLE
Headaer Images aren't being pulled in

### ISSUE THREAD

**Issue by jason-faithinkids** [Alasdair-Munday/build24-advent#2]
**Describe the bug**
I've checked the WP plugin & for those with images - the URL is present in the field, but does not show on the page. 
EG. Day 2 has the img [URL](https://kingdomcode.faithinkids.org/wp-content/uploads/2024/10/2.png) but does not show 
[here] (https://christmasbuildup.netlify.app/posts/day2/)

**Expected behavior**
Update URL on the post plugin and it updates the page with the image loaded in

**Comment by Alasdair-Munday** [comment]
I believe I've fixed this in the plugin PR
