### ISSUE TITLE
Sticker book sticker placing

### ISSUE THREAD

**Issue by LizzieFaithinKids** [Alasdair-Munday/build24-advent#28]
Is it possible to increase the size of the area where stickers can be placed, on mobile it is very small and so will be hard to place all the stickers.
![IMG_2374](https://github.com/user-attachments/assets/2eb576fb-44f3-408c-b417-be144f2895d5)

**Comment by Alasdair-Munday** [comment]
also we'll add a background to make the sticker area clearer
